"use client";
import { FormEvent, useEffect, useState } from "react";
import { Plus, Trash2, X } from "lucide-react";
import AppShell from "@/components/AppShell";
import { api } from "@/lib/api";
import { Tenant } from "@/lib/types";
const blank = { fullName: "", phone: "", identityNumber: "", email: "", permanentAddress: "", loginPassword: "" };
export default function TenantsPage() { const [items, setItems] = useState<Tenant[]>([]), [form,setForm] = useState(blank), [open,setOpen] = useState(false), [error,setError] = useState(""); const load=()=>api<Tenant[]>("/tenants").then(setItems).catch(e=>setError(e.message)); useEffect(()=>{ void load(); },[]);
 async function save(e:FormEvent){e.preventDefault(); try{await api("/tenants",{method:"POST",body:JSON.stringify(form)});setOpen(false);setForm(blank);load()}catch(e){setError(e instanceof Error?e.message:"Không thể lưu")}}
 async function remove(id:string){if(!confirm("Xóa khách thuê này?"))return;try{await api(`/tenants/${id}`,{method:"DELETE"});load()}catch(e){setError(e instanceof Error?e.message:"Không thể xóa")}}
 return <AppShell title="Khách thuê" action={<button className="btn btn-primary" onClick={()=>setOpen(true)}><Plus size={17}/>Thêm khách thuê</button>}>{error&&<p className="mb-4 text-red-600">{error}</p>}<section className="panel overflow-x-auto"><table><thead><tr><th>Họ tên</th><th>Điện thoại</th><th>CCCD/CMND</th><th>Email</th><th>Phòng hiện tại</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td className="font-semibold">{x.fullName}</td><td>{x.phone}</td><td>{x.identityNumber}</td><td>{x.email||"-"}</td><td>{x.contracts?.[0]?.room?.code||"Chưa gán"}</td><td><button title="Xóa khách thuê" className="btn btn-danger p-2" onClick={()=>remove(x.id)}><Trash2 size={16}/></button></td></tr>)}</tbody></table></section>{open&&<div className="fixed inset-0 z-10 grid place-items-center bg-slate-950/30 p-4"><form onSubmit={save} className="panel w-full max-w-xl p-5 shadow-xl"><div className="mb-4 flex justify-between"><h2 className="font-bold">Thêm khách thuê</h2><button title="Đóng" type="button" onClick={()=>setOpen(false)}><X size={20}/></button></div><div className="grid gap-4 sm:grid-cols-2"><div><label>Họ tên</label><input required value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></div><div><label>Số điện thoại</label><input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div><label>CCCD/CMND</label><input required value={form.identityNumber} onChange={e=>setForm({...form,identityNumber:e.target.value})}/></div><div><label>Email (tạo tài khoản)</label><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div></div><div className="mt-4"><label>Địa chỉ thường trú</label><input value={form.permanentAddress} onChange={e=>setForm({...form,permanentAddress:e.target.value})}/></div><div className="mt-4"><label>Mật khẩu đăng nhập Tenant (bỏ trống nếu chưa tạo tài khoản)</label><input type="password" value={form.loginPassword} onChange={e=>setForm({...form,loginPassword:e.target.value})}/></div><div className="mt-5 flex justify-end gap-2"><button type="button" className="btn btn-quiet" onClick={()=>setOpen(false)}>Hủy</button><button className="btn btn-primary">Lưu khách thuê</button></div></form></div>}</AppShell> }
