"use client";
import { FormEvent, useEffect, useState } from "react";
import { Pencil, Plus, Trash2, X } from "lucide-react";
import AppShell from "@/components/AppShell";
import { api, money } from "@/lib/api";
import { Room } from "@/lib/types";

const blank = { code: "", name: "", monthlyRent: 3000000, status: "Available", notes: "" };
const labels: Record<string, string> = { Available: "Trống", Occupied: "Đang thuê", Maintenance: "Bảo trì" };
export default function RoomsPage() {
  const [items, setItems] = useState<Room[]>([]), [form, setForm] = useState(blank), [editing, setEditing] = useState<Room | null>(null), [open, setOpen] = useState(false), [error, setError] = useState("");
  const load = () => api<Room[]>("/rooms").then(setItems).catch(e => setError(e.message)); useEffect(() => { void load(); }, []);
  function show(room?: Room) { setEditing(room ?? null); setForm(room ? { code: room.code, name: room.name, monthlyRent: room.monthlyRent, status: room.status, notes: room.notes ?? "" } : blank); setOpen(true); }
  async function save(e: FormEvent) { e.preventDefault(); try { await api(editing ? `/rooms/${editing.id}` : "/rooms", { method: editing ? "PUT" : "POST", body: JSON.stringify(form) }); setOpen(false); load(); } catch (e) { setError(e instanceof Error ? e.message : "Không thể lưu."); } }
  async function remove(id: string) { if (!confirm("Xóa phòng này?")) return; try { await api(`/rooms/${id}`, { method: "DELETE" }); load(); } catch (e) { setError(e instanceof Error ? e.message : "Không thể xóa."); } }
  return <AppShell title="Phòng trọ" action={<button className="btn btn-primary" onClick={() => show()}><Plus size={17}/>Thêm phòng</button>}>{error && <p className="mb-4 text-red-600">{error}</p>}<section className="panel overflow-x-auto"><table><thead><tr><th>Mã phòng</th><th>Tên phòng</th><th>Giá thuê</th><th>Trạng thái</th><th>Ghi chú</th><th></th></tr></thead><tbody>{items.map(room => <tr key={room.id}><td className="font-bold">{room.code}</td><td>{room.name}</td><td>{money(room.monthlyRent)}</td><td><span className={`badge ${room.status === "Available" ? "bg-teal-100 text-teal-800" : room.status === "Occupied" ? "bg-sky-100 text-sky-800" : "bg-amber-100 text-amber-800"}`}>{labels[room.status]}</span></td><td className="max-w-48 overflow-hidden text-ellipsis">{room.notes || "-"}</td><td><div className="flex gap-2"><button title="Sửa phòng" className="btn btn-quiet p-2" onClick={() => show(room)}><Pencil size={16}/></button><button title="Xóa phòng" className="btn btn-danger p-2" onClick={() => remove(room.id)}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></section>{open && <div className="fixed inset-0 z-10 grid place-items-center bg-slate-950/30 p-4"><form onSubmit={save} className="panel w-full max-w-lg p-5 shadow-xl"><div className="mb-4 flex justify-between"><h2 className="font-bold">{editing ? "Cập nhật phòng" : "Thêm phòng mới"}</h2><button title="Đóng" type="button" onClick={() => setOpen(false)}><X size={20}/></button></div><div className="grid gap-4 sm:grid-cols-2"><div><label>Mã phòng</label><input required value={form.code} onChange={e => setForm({...form, code:e.target.value})}/></div><div><label>Tên phòng</label><input required value={form.name} onChange={e => setForm({...form, name:e.target.value})}/></div><div><label>Giá thuê/tháng</label><input required min="0" type="number" value={form.monthlyRent} onChange={e => setForm({...form, monthlyRent:+e.target.value})}/></div><div><label>Trạng thái</label><select value={form.status} onChange={e => setForm({...form, status:e.target.value})}><option value="Available">Trống</option><option value="Occupied">Đang thuê</option><option value="Maintenance">Bảo trì</option></select></div></div><div className="mt-4"><label>Ghi chú</label><textarea value={form.notes} onChange={e => setForm({...form, notes:e.target.value})}/></div><div className="mt-5 flex justify-end gap-2"><button type="button" className="btn btn-quiet" onClick={() => setOpen(false)}>Hủy</button><button className="btn btn-primary">Lưu phòng</button></div></form></div>}</AppShell>;
}
