"use client";
import { useEffect, useState } from "react";
import { CircleDollarSign, DoorOpen, ReceiptText, TriangleAlert } from "lucide-react";
import AppShell from "@/components/AppShell";
import { api, money } from "@/lib/api";

type Dashboard = { billingMonth: string; monthlyRevenue: number; outstandingAmount: number; vacantRooms: number; occupiedRooms: number; openTickets: number; unpaidInvoices: { id: string; roomCode: string; tenantName: string; totalAmount: number; dueDate: string; status: string }[] };
const cards = [["Doanh thu đã thu", "monthlyRevenue", CircleDollarSign, "text-teal-700"], ["Còn phải thu", "outstandingAmount", ReceiptText, "text-rose-600"], ["Phòng trống", "vacantRooms", DoorOpen, "text-sky-600"], ["Sự cố chưa xong", "openTickets", TriangleAlert, "text-amber-600"]] as const;
export default function DashboardPage() { const [data, setData] = useState<Dashboard | null>(null); const [error, setError] = useState(""); useEffect(() => { api<Dashboard>("/dashboard").then(setData).catch(e => setError(e.message)); }, []); return <AppShell title="Tổng quan">{error ? <p className="text-red-600">{error}</p> : !data ? <p>Đang tải...</p> : <><section className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, key, Icon, color]) => <article className="panel p-4" key={key}><div className="flex items-center justify-between"><span className="text-sm text-slate-500">{label}</span><Icon className={color} size={21}/></div><p className="mt-3 text-2xl font-bold">{key.includes("Amount") || key === "monthlyRevenue" ? money(data[key]) : data[key]}</p></article>)}</section><section className="panel overflow-x-auto"><div className="border-b border-slate-200 p-4 font-bold">Hóa đơn chưa thanh toán</div><table><thead><tr><th>Phòng</th><th>Khách thuê</th><th>Hạn thanh toán</th><th>Số tiền</th><th>Trạng thái</th></tr></thead><tbody>{data.unpaidInvoices.length === 0 ? <tr><td colSpan={5} className="text-center text-slate-500">Không có hóa đơn chưa thanh toán.</td></tr> : data.unpaidInvoices.map(item => <tr key={item.id}><td>{item.roomCode}</td><td>{item.tenantName}</td><td>{new Date(item.dueDate).toLocaleDateString("vi-VN")}</td><td className="font-semibold">{money(item.totalAmount)}</td><td><span className="badge bg-amber-100 text-amber-800">Chưa trả</span></td></tr>)}</tbody></table></section></>}</AppShell>; }
